name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Deploy to GitHub Pages
        if: success()
        run: |
          npm install
          npm run build
          npm run deploy
        working-directory: ./simple-calculator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
